version: 2
updates:
  - package-ecosystem: npm
    directory: "/ui/extensions/charlotte-toolkit-ui/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
      timezone: "UTC"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
      timezone: "UTC"
